:doctype: book
:toc: right
:toclevels: 4
:numbered:
:sectlink:
:sectanchors:
:sectid:
:icons: font
:source-language: java
:source-highlighter: highlight.js

= CDI 1.2 User guide
Antoine Sabot-Durand <asd@redhat.com>; Martin Kouba <mkouba@redhat.com>; Matej Novotny <mnovotny@redhat.com>; Tomas Remes <tremes@redhat.com>
v1.0, May 2016


[preface]
= Foreword

This documentation is a fork of the Weld (CDI Refererence implementation) documentation.
We removed all Weld specific mention to provide readers a good introduction to CDI programming model.

If this documentation is maintained by the authors listed above its title, it is a collective work including the following people:

* Jozef Hartinger
* Pete Muir
* Dan Allen
* David Allen
* Gavin King

While this documentation is probably easier to read than the specification, we encourage you http://docs.jboss.org/cdi/spec/1.2/cdi-spec.html[to give a look at it^], should you need deeper understanding of the CDI platform.

The source of this guide is available on https://github.com/cdi-spec/cdi-user-guide[github]
Feel free to fill ticket or send PR if you want to make this document better.




include::part1.asciidoc[]

//include::part2.asciidoc[] TBD

include::part3.asciidoc[]

include::part4.asciidoc[]

